#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""鸿蒙微内核 ABI 规格书 - 正文生成（ReportLab, TocDocTemplate）"""
import json
import hashlib
import os
import sys

PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, "scripts"))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, PageBreak, KeepTogether)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f4f3f3')
SECTION_BG    = colors.HexColor('#f2f1f0')
CARD_BG       = colors.HexColor('#f0efeb')
TABLE_STRIPE  = colors.HexColor('#f5f4f3')
HEADER_FILL   = colors.HexColor('#696047')
COVER_BLOCK   = colors.HexColor('#847b5f')
BORDER        = colors.HexColor('#d4d1c9')
ICON          = colors.HexColor('#897b51')
ACCENT        = colors.HexColor('#8e7324')
ACCENT_2      = colors.HexColor('#6f57b8')
TEXT_PRIMARY  = colors.HexColor('#1c1c1a')
TEXT_MUTED    = colors.HexColor('#78766f')

FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('SarasaMonoSC', f'{FONT_DIR}/truetype/chinese/SarasaMonoSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('SarasaMonoSC-Bold', f'{FONT_DIR}/truetype/chinese/SarasaMonoSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('SarasaMonoSC', normal='SarasaMonoSC', bold='SarasaMonoSC-Bold')

from pdf import install_font_fallback
install_font_fallback()

DATA = json.load(open('/home/z/my-project/hongmeng-abi-spec/abi_inventory.json'))
OUT = '/home/z/my-project/hongmeng-abi-spec/body.pdf'

# ---------- styles ----------
S_BODY = ParagraphStyle('Body', fontName='NotoSerifSC', fontSize=10.5, leading=17,
                        alignment=TA_LEFT, wordWrap='CJK', firstLineIndent=21,
                        spaceAfter=8, textColor=TEXT_PRIMARY)
S_BODY_NI = ParagraphStyle('BodyNI', parent=S_BODY, firstLineIndent=0)
S_H1 = ParagraphStyle('H1', fontName='NotoSerifSC-Bold', fontSize=17, leading=24,
                      spaceBefore=18, spaceAfter=10, textColor=TEXT_PRIMARY, wordWrap='CJK')
S_H2 = ParagraphStyle('H2', fontName='NotoSerifSC-Bold', fontSize=13, leading=19,
                      spaceBefore=14, spaceAfter=8, textColor=TEXT_PRIMARY, wordWrap='CJK')
S_CAP = ParagraphStyle('Cap', fontName='NotoSerifSC', fontSize=9, leading=13,
                       alignment=TA_CENTER, textColor=TEXT_MUTED, spaceBefore=3, spaceAfter=6)
S_CELL = ParagraphStyle('Cell', fontName='NotoSerifSC', fontSize=9, leading=13,
                        wordWrap='CJK', textColor=TEXT_PRIMARY)
S_CELL_C = ParagraphStyle('CellC', parent=S_CELL, alignment=TA_CENTER)
S_CELL_HD = ParagraphStyle('CellHd', fontName='NotoSerifSC-Bold', fontSize=9.5, leading=13,
                           wordWrap='CJK', alignment=TA_CENTER, textColor=colors.white)
S_MONO = ParagraphStyle('Mono', fontName='SarasaMonoSC', fontSize=8.5, leading=12.5,
                        wordWrap='CJK', textColor=TEXT_PRIMARY)
S_NOTE = ParagraphStyle('Note', fontName='NotoSerifSC', fontSize=9.5, leading=15,
                        wordWrap='CJK', textColor=TEXT_MUTED, spaceAfter=6)

def P(t, s=S_BODY):
    return Paragraph(t, s)

def heading(text, style, level=0):
    key = 'h_' + hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph(f'<a name="{key}"/>{text}', style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def make_table(header, rows, widths, header_bg=HEADER_FILL):
    data = [[Paragraph(h, S_CELL_HD) for h in header]]
    for r in rows:
        data.append([c if isinstance(c, Paragraph) else Paragraph(str(c), S_CELL) for c in r])
    tw = sum(widths)
    avail = A4[0] - 40 * mm
    if tw < avail * 0.85 or tw > avail:
        widths = [w * (avail * 0.98) / tw for w in widths]
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    st = [('BACKGROUND', (0, 0), (-1, 0), header_bg),
          ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
          ('TOPPADDING', (0, 0), (-1, -1), 4),
          ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
          ('LEFTPADDING', (0, 0), (-1, -1), 5),
          ('RIGHTPADDING', (0, 0), (-1, -1), 5),
          ('LINEBELOW', (0, 0), (-1, 0), 0.8, header_bg),
          ('LINEBELOW', (0, -1), (-1, -1), 0.5, BORDER),
          ('LINEABOVE', (0, 0), (-1, 0), 0.5, BORDER)]
    for i in range(1, len(data)):
        if i % 2 == 0:
            st.append(('BACKGROUND', (0, i), (-1, i), TABLE_STRIPE))
    t.setStyle(TableStyle(st))
    return t

def callout(items):
    """数字卡片行: items = [(num, label), ...]"""
    cells = []
    w = (A4[0] - 40 * mm) / len(items)
    for num, label in items:
        inner = Table([[Paragraph(num, ParagraphStyle('N', fontName='NotoSerifSC-Bold',
                                                      fontSize=17, leading=21, alignment=TA_CENTER,
                                                      textColor=HEADER_FILL))],
                       [Paragraph(label, ParagraphStyle('L', fontName='NotoSerifSC', fontSize=8.5,
                                                        leading=12, alignment=TA_CENTER,
                                                        wordWrap='CJK', textColor=TEXT_MUTED))]],
                      colWidths=[w - 6])
        inner.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
                                   ('TOPPADDING', (0, 0), (-1, 0), 8),
                                   ('BOTTOMPADDING', (0, -1), (-1, -1), 8),
                                   ('TOPPADDING', (0, 1), (-1, 1), 2)]))
        cells.append(inner)
    t = Table([cells], colWidths=[w] * len(items), hAlign='CENTER')
    t.setStyle(TableStyle([('LEFTPADDING', (0, 0), (-1, -1), 3),
                           ('RIGHTPADDING', (0, 0), (-1, -1), 3),
                           ('VALIGN', (0, 0), (-1, -1), 'TOP')]))
    return t

# ---------- footer ----------
def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont('NotoSerifSC', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(20 * mm, 12 * mm, '鸿蒙微内核 ABI 规格书')
    canvas.setFont('FreeSerif', 9)
    canvas.drawRightString(A4[0] - 20 * mm, 12 * mm, str(canvas.getPageNumber()))
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(20 * mm, 16 * mm, A4[0] - 20 * mm, 16 * mm)
    canvas.restoreState()

class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

doc = TocDocTemplate(OUT, pagesize=A4,
                     leftMargin=20 * mm, rightMargin=20 * mm,
                     topMargin=22 * mm, bottomMargin=20 * mm,
                     title='鸿蒙微内核 ABI 规格书', author='Z.ai')

story = []

# ===== 目录 =====
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle('T0', fontName='NotoSerifSC-Bold', fontSize=11.5, leading=20,
                   leftIndent=6, textColor=TEXT_PRIMARY),
    ParagraphStyle('T1', fontName='NotoSerifSC', fontSize=10, leading=17,
                   leftIndent=22, textColor=TEXT_PRIMARY),
]
story.append(Paragraph('目录', ParagraphStyle('TT', fontName='NotoSerifSC-Bold',
                                              fontSize=17, leading=24, spaceAfter=12,
                                              textColor=TEXT_PRIMARY)))
story.append(toc)
story.append(PageBreak())

caps = sorted(DATA['capability_types'], key=lambda x: x['cap_id'])
ops = DATA['numbered_ops']
meta = DATA['meta']
ls = DATA['lsyscalls']
lsc = DATA.get('lsyscalls_compat', [])
ba = DATA['bootargs']

# ===== 第一章 =====
story.append(heading('第一章　规格总览与核心结论', S_H1, 0))
story.append(P('本规格书从 HarmonyOS 官方开源合规包（SCA-AL00，HarmonyOS 6.1.0）中的'
               '微内核项目 hm-verif-kernel 公开头文件出发，对其应用二进制接口（ABI）做机器化提取与归档。'
               '提取对象覆盖内核 UAPI 头（kernel/include/mapi/uapi）与架构侧 UAPI 头'
               '（kernel/arch/aarch64/include/mapi/uapi），目标是回答一个问题：'
               '闭源的微内核本体，其对外契约到底被公开部分钉死了多少，以及按这些契约重实现一个'
               'ABI 兼容内核的可行性与工作量。'))
story.append(Spacer(1, 6))
story.append(callout([('197', 'UAPI 头文件'),
                      ('21', '能力对象类型'),
                      ('819', '编号操作（76 张表）'),
                      ('705', 'Linux 兼容系统调用')]))
story.append(Spacer(1, 10))
story.append(P('核心结论有四条。第一，该内核的能力对象类型系统被 CAPTYPE 宏体系完整公开：'
               '21 个类型、每个类型的数字编号、授权粒度（细粒度/粗粒度/禁授权）、方法表与类型化错误码全部可还原，'
               '这相当于把整个内核的对象模型交了出来。第二，快速通道（fastcall）操作以编号常量形式公开，'
               'ctrlmem 页表快速通道 14 个编号操作、SMMU 快速通道 21 个操作构成最小可执行回路的全部入口。'
               '第三，Linux 兼容层直接复用 Linux 系统调用编号（313 个主编号加 392 个兼容编号），'
               '并以编译期断言锁定，用户态二进制的系统调用兼容性是被保证的。第四，'
               '头文件钉死的是"接口与 ABI"；调度策略、页分配算法、异常向量等"语义与实现"不在其中，'
               '这些构成重实现的全部工作量。', S_BODY))
story.append(P('需要特别说明的是能力类型编号中 16 号的缺席：21 个公开类型的编号为 1 至 15 与 17 至 22，'
               '16 号没有任何公开头文件定义。这要么是保留编号，要么对应某个完全未公开的内核对象类型，'
               '它本身即是内核结构的旁证之一。'))

# ===== 第二章 =====
story.append(heading('第二章　数据来源与提取方法', S_H1, 0))
story.append(heading('2.1　数据来源', S_H2, 1))
story.append(P('全部数据来自官方开源合规包内的两个目录树：其一为 kernel/include/mapi，'
               '包含 UAPI 子树（197 个头文件，面向用户态的稳定接口）与内核侧 mapi/hmkernel 子树；'
               '其二为 kernel/arch/aarch64/include/mapi，包含 ARM64 架构相关的 UAPI 头，'
               '其中 hmasm/boot/sysproc_bootargs.h 定义了引导交接布局，hmasm/lscno_def.h 定义了'
               'Linux 兼容系统调用编号。为便于复核，原始路径在清单 JSON 中逐条保留。'))
story.append(heading('2.2　提取规则', S_H2, 1))
story.append(P('提取器（extract_abi.py，随本规格书一同交付）按五类规则工作：'
               'CAPTYPE 宏解析能力类型及其授权与方法表；编号宏扫描捕获 #define __前缀_操作 数字 形式的'
               '快速通道编号；枚举扫描捕获 enum __xxx_cmd 形式的操作表（如 SMMU）；'
               'LSCNO_DEF 与 LSCNO_COMPAT_DEF 捕获 Linux 兼容系统调用编号；'
               '断言宏扫描统计结构布局的编译期校验。方法的注释级分类（capcall 专有/兼备 fastcall）'
               '保留在原始头文件中，提取器不猜测语义。'))
story.append(P('已知局限有三：条件编译分支未逐一展开，少数表格的取值以宏表达式给出而未捕获；'
               'CAPERRNO 之外的内联注释不进入清单；架构侧头文件仅处理 AArch64。'
               '这些局限影响覆盖率的绝对数值，不影响接口存在性判定。', S_BODY))

# ===== 第三章 =====
story.append(heading('第三章　能力类型系统', S_H1, 0))
story.append(P('能力（capability）是该内核一切特权操作的通行证：线程、地址空间、中断控制器、'
               '调度器都是能力对象，持有能力方可调用对应方法。CAPTYPE 宏为每个类型给出三件事：'
               '数字编号（出现在内核对象头与授权检查中）、授权策略（CAPFINEGRANT 细粒度、'
               'CAPCOARSEGRANT 粗粒度、CAPNOGRANT 禁止授权，以及 GRANTMOVE 变体）、'
               '与方法表（每个方法对应一个 capcall/fastcall 编号）。下表为 21 个类型的完整清单。'))
rows = []
for c in caps:
    grants = ','.join(g.replace('CAP', '').replace('GRANT', '') for g in c['grant'])
    gm = ','.join(g.replace('CAP', '').replace('GRANTMOVE', '') for g in c['grant_move'])
    rows.append([c['cap_id'], c['name'], grants or '-', gm or '-',
                 c['method_count'], len(c.get('errnos', []))])
story.append(make_table(['编号', '类型', '授权粒度', '授权移动', '方法数', '错误码'],
                        rows, [14*mm, 34*mm, 30*mm, 30*mm, 22*mm, 22*mm]))
story.append(Paragraph('表 3-1　能力对象类型全表（编号 16 缺席）', S_CAP))
story.append(P('从规模看，SysCtrl（67 个方法）是系统控制中枢，覆盖电源、时钟、复位等平台级操作；'
               'CNode（44 个方法）是能力容器本身，负责能力的复制、吊销与传递；'
               'Thread（45 个方法）支持唤醒、挂起、绑定 CPU、名字设置等完整线程控制面。'
               '从授权策略看，Thread 与 VM 选择粗粒度授权并禁止授权移动，'
               '而 IrqCtrl 选择细粒度授权且允许全部授权移动并禁用默认查找——中断能力可以在进程间'
               '精确移交，这与用户态驱动框架（devhost/UDK）持有中断能力的设计互为印证。'))
story.append(P('以 Thread 类型为例，其配置字以 32 位高位掩码表达创建语义：'
               '调用者地址空间共享（0x1）、创建即挂起（0x2）、克隆用户上下文（0x4）、'
               'vfork（0x40）、内核辅助线程（0x1000）、fork 时复位（0x2000）等。'
               '这些位域与 Linux 的 clone 标志存在清晰的映射关系，是 sysmgr 实现 fork/clone 语义的基石。'))

# ===== 第四章 =====
story.append(heading('第四章　快速通道编号表', S_H1, 0))
story.append(P('除能力方法外，内核以编号常量暴露快速通道操作。全库共提取 76 张表、819 条编号，'
               '按规模排序的主要表格如下。其中 CTRLMEM 一张表即含 176 条，原因是它同时编码了'
               '命令号与位域掩码（如页表项访问位、只读位的置位/清除掩码），把"命令+参数编码"全部宏化。'))
top = sorted(ops.items(), key=lambda kv: -len(kv[1]))[:10]
story.append(make_table(['编号表', '条数', '所在头文件（首个）'],
                        [[k, len(v), v[0]['header'].replace('hmkernel/', '')] for k, v in top],
                        [40*mm, 22*mm, 92*mm]))
story.append(Paragraph('表 4-1　编号表规模排行（前十）', S_CAP))
story.append(heading('4.1　ctrlmem 页表快速通道', S_H2, 1))
story.append(P('ctrlmem 是内核与 sysmgr 之间的控制内存机制，其系统调用子表定义了 14 个编号操作，'
               '构成地址空间管理的快速路径：映射用户页（MAP_PGVA）、批量映射（BATCH_MAP_PGVA）、'
               'TLB 聚合卸载（TLBGATHER_UNMAP）、区间保护修改（RANGE_MPROTECT）、区间卸载（RANGE_MUNMAP）、'
               '页串映射（MAP_PGSTRVA）等。这组编号就是 sysmgr 代替内核管理页表时的全部入口。'))
c14 = [e for e in ops.get('CTRLMEM', []) if e['op'].startswith('SYSCALL') and e['value'] < 20]
story.append(make_table(['编号', '操作'],
                        [[e['value'], '__CTRLMEM_' + e['op']] for e in c14],
                        [22*mm, 132*mm]))
story.append(Paragraph('表 4-2　ctrlmem 快速通道系统调用（14 个编号操作）', S_CAP))
story.append(heading('4.2　SMMU 快速通道', S_H2, 1))
smmu = ops.get('SMMU', [])
story.append(P('SMMU（IOMMU）命令表以枚举形式公开，21 个操作覆盖设备attach、映射与批量映射、'
               'IOVA 反查物理地址、TLB 按上下文失效、TTW 刷新、TCU 电源管理、PMU 配置等。'
               '用户态驱动申请映射、内核独占页表的权力结构，在编号层面一目了然。'))
story.append(make_table(['值', '命令', '语义'],
                        [[e['value'], '__SMMU_' + e['op'],
                          {'MAP': '建立映射', 'UNMAP': '解除映射', 'MAP_SG': '散列表映射',
                           'MAP_BATCH': '批量映射', 'UNMAP_BATCH': '批量解除',
                           'IOVA_TO_PHYS': 'IOVA 反查物理地址', 'ATTACH_DEV': '设备挂接域',
                           'TLB_INV_CONTEXT': '按上下文失效 TLB', 'TCU_POWER_ON': 'TCU 上电',
                           'GET_TTBR': '读取 TTBR', 'UNMAP_INV_CACHE': '解除映射并失效缓存'
                          }.get(e['op'], '')] for e in smmu],
                        [14*mm, 62*mm, 68*mm]))
story.append(Paragraph('表 4-3　SMMU 快速通道命令表（21 个操作）', S_CAP))

# ===== 第五章 =====
story.append(heading('第五章　Linux 兼容系统调用层', S_H1, 0))
story.append(P('lscno_def.h 以 LSCNO_DEF(名称, 编号) 的形式定义了 313 个本地系统调用，'
               '另有 392 个兼容编号（LSCNO_COMPAT_DEF）。机制上，内核侧以枚举生成 __NR_ 与 __SYS_ 双前缀常量，'
               '用户态则用 raw_static_assert 断言与 glibc 的 __NR_ 编号逐一相等——'
               '也就是说 liblinux 载入的 Linux 程序与驱动发起系统调用时，编号无需翻译直接进入兼容层，'
               '兼容性由编译期锁定而非运行期约定。'))
story.append(P('编号表内容从 io_setup（0 号）起按 Linux aarch64 通用编号排列，覆盖文件、'
               '内存、进程、信号、网络全套。这一层与 devhost 的 liblinux 后端互为表里：'
               '前者是系统调用的"号"，后者是系统调用的"实现"。', S_BODY))
story.append(make_table(['项目', '数值', '说明'],
                        [['主编号', str(len(ls)), 'LSCNO_DEF，与 Linux __NR_ 对齐'],
                         ['兼容编号', str(len(lsc)), 'LSCNO_COMPAT_DEF，32 位兼容路径'],
                         ['编号起点', str(ls[0]['nr']) if ls else '-', 'io_setup'],
                         ['锁定方式', 'raw_static_assert', '用户侧编译期断言一致']],
                        [30*mm, 26*mm, 88*mm]))
story.append(Paragraph('表 5-1　lsyscall 层概览', S_CAP))

# ===== 第六章 =====
story.append(heading('第六章　引导交接与布局断言', S_H1, 0))
story.append(P('sysproc_bootargs.h 定义了微内核移交给首个系统进程（sysmgr）的 72 字节引导参数结构，'
               '并以编译期断言锁定每个字段的偏移。这份"禅让诏书"是内核与系统服务器之间的第一契约：'
               '内核完成早期汇编与初始页表构建后，将根页表、用户程序区间、安全策略库虚拟地址一并移交。'))
story.append(make_table(['字段', '偏移(字节)', '语义'],
                        [[f['field'], f['offset'], 
                          {'load_start': '映像加载起始地址', 'canary': '栈保护金丝雀值',
                           'superpolicydb_va_st': 'SELinux 超级策略库虚拟地址（可选）',
                           'pgd': '根页表基地址', 'uapps_start': '用户程序区间起点',
                           'uapps_end': '用户程序区间终点', 'mmap_rnd': 'mmap 随机化熵'
                          }.get(f['field'], '')] for f in ba.get('fields', [])],
                        [40*mm, 22*mm, 82*mm]))
story.append(Paragraph('表 6-1　sysproc 引导参数布局（结构总长 72 字节，10 处断言）', S_CAP))
story.append(P('结构开头两个指令字保留为 nop 与跳转指令，供内核跳入 sysmgr 的 head.S；'
               '配置了策略库字段时（CONFIG_POLICYDB_USE_SUPERVS），SELinux 策略数据库的虚拟地址'
               '在第 32 字节处交付。这一设计把"安全策略随内核引导"写进了 ABI。', S_BODY))

# ===== 第七章 =====
story.append(heading('第七章　声明面统计与开源边界', S_H1, 0))
story.append(P('按子系统统计 UAPI 头中的函数声明共 2,361 处。追踪类（trace/events）占大头，'
               '这反映内核的可观测性设计：跟踪点作为稳定 ABI 交付。核心声明集中在页表处理、'
               '控制内存与能力目录，与第三、四章的编号表互为印证。'))
decls = list(DATA['declarations'].items())[:8]
story.append(make_table(['子系统', '声明数'],
                        [[k, v] for k, v in decls], [60*mm, 30*mm]))
story.append(Paragraph('表 7-1　函数声明按子系统分布（前八）', S_CAP))
story.append(P('结合本系列分析的整体结论，开源边界如下表所示。头文件交付的是完整 ABI：'
               '对象模型（第三章）、快速通道（第四章）、系统调用编号（第五章）、引导契约（第六章）。'
               '闭源的微内核与 sysmgr 二进制，恰好处在这份规格书的每一行约束之下。', S_BODY))
story.append(make_table(['组件', '状态', '本规格书覆盖'],
                        [['微内核本体（调度/内存/能力运行时）', '闭源', 'ABI 全覆盖'],
                         ['sysmgr 系统服务器', '闭源', 'intapi 契约覆盖'],
                         ['UAPI 头（465 个）', '开源', '本文数据源'],
                         ['用户态世界（devhost/UDK/liblinux）', '开源', '消费方佐证']],
                        [62*mm, 20*mm, 62*mm]))
story.append(Paragraph('表 7-2　开源边界与本规格书的覆盖关系', S_CAP))

# ===== 第八章 =====
story.append(heading('第八章　重实现路线评估', S_H1, 0))
story.append(P('以 ABI 兼容为目标重实现该内核，可行性取决于三点：契约完备度、调用方可观测性、'
               '工作量量级。契约完备度方面，本规格书显示对象模型与快速通道均已钉死；'
               '调用方可观测性方面，devhost/UDK/liblinux 全部开源，构成最苛刻的测试用例来源；'
               '工作量方面，缺口的全部在实现语义：调度策略、物理页分配、TLB 与缓存维护、'
               '异常向量与上下文切换、GICv3/SMMUv3 内核侧驱动、能力运行时的授权与吊销逻辑。'))
story.append(make_table(['里程碑', '内容', '依赖规格'],
                        [['M1 最小回路', '启动、CNode/Thread 能力、ctrlmem 映射', '第三、四、六章'],
                         ['M2 系统进程', 'bootargs 移交、sysmgr 存根、页表服务', '第六章'],
                         ['M3 兼容层', 'lsyscall 透传 + libdh-linux 载入', '第五章'],
                         ['M4 驱动栈', 'devhost + SMMU/irq 能力交付', '第四章']],
                        [30*mm, 68*mm, 46*mm]))
story.append(Paragraph('表 8-1　重实现里程碑路线（研究性重建口径）', S_CAP))
story.append(P('合规边界需要明确：重实现只能以公开头文件与开源调用方为规格来源，'
               '不得反汇编闭源二进制，不得使用任何泄露实现（本系列已证实泄露包亦无内核实现），'
               '产物不得使用 HarmonyOS 或鸿蒙商标。此路线与 Wine、ReactOS 等先例的合法实践一致。'
               '工作量量级按 seL4 参照折算，研究性重建的最小回路为个人年级别，'
               '完整 ABI 兼容替换为三至五人年级别。', S_BODY))

# ===== 附录 =====
story.append(heading('附录　清单文件使用说明', S_H1, 0))
story.append(P('随本规格书交付机器可读清单 abi_inventory.json（约 147KB）与提取器 extract_abi.py。'
               '清单顶层键为：meta（统计元数据）、capability_types（能力类型数组，含 cap_id、name、'
               'grant、grant_move、methods、errnos、flags）、numbered_ops（编号表字典，键为表前缀，'
               '值为 op/value/header 列表）、lsyscalls 与 lsyscalls_compat（Linux 兼容编号数组）、'
               'bootargs（引导参数字段与偏移）、layout_asserts（布局断言分布）、declarations'
               '（声明按子系统统计）。提取器用法：python3 extract_abi.py <mapi目录> <arch include 目录>，'
               '可在新版本源码包上直接重跑以做版本间 ABI 对比。', S_BODY_NI))

doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print('body OK ->', OUT)
